### ISSUE TITLE
Error buying storage

### ISSUE THREAD

**Issue by KeeferGeek** [crashtheparty/ColdStorage#2]
Going through the process to purchase a storage on my server running PaperMC 1.14.2 and when I get to the step where I should be able to buy the actual storage, the buy button is missing. The server log gives me the following error the second I get to this screen:

> [15:57:06 ERROR]: Could not pass event InventoryClickEvent to ColdStorage v2.0.1
java.lang.NullPointerException: null
        at org.ctp.coldstorage.storage.Draft.tooManyType(Draft.java:120) ~[?:?]
        at org.ctp.coldstorage.storage.Draft.canBuy(Draft.java:149) ~[?:?]
        at org.ctp.coldstorage.inventory.draft.ViewDraft.setInventory(ViewDraft.java:149) ~[?:?]
        at org.ctp.coldstorage.utils.inventory.InventoryUtils.addInventory(InventoryUtils.java:112) ~[?:?]
        at org.ctp.coldstorage.inventory.draft.DraftList.editDraft(DraftList.java:181) ~[?:?]
        at org.ctp.coldstorage.utils.inventory.InventoryClickUtils.viewDraftList(InventoryClickUtils.java:241) ~[?:?]
        at org.ctp.coldstorage.listeners.InventoryClick.onInventoryClick(InventoryClick.java:56) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor111.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-65]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-65]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-65]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2342) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:998) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:991) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:115) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:975) ~[patched_1.14.2.jar:git-Paper-65]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.2.jar:git-Paper-65]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]

**Comment by kassadGLA** [comment]
Confirm this. `NullPointerException` every click on any item in the gui where player creating draft.
Also I get a warn in console:
```yaml
[21:55:07 WARN]: [ColdStorage] Task #4414 for ColdStorage v2.0.2 generated an exception
java.lang.NullPointerException: null
        at org.ctp.coldstorage.database.tables.StorageTypeTable.hasStorageType(StorageTypeTable.java:110) ~[?:?]
        at org.ctp.coldstorage.database.tables.StorageTypeTable.getPermissions(StorageTypeTable.java:292) ~[?:?]
        at org.ctp.coldstorage.utils.DatabaseUtils.getStringPermissions(DatabaseUtils.java:163) ~[?:?]
        at org.ctp.coldstorage.storage.Draft.zeroType(Draft.java:139) ~[?:?]
        at org.ctp.coldstorage.storage.Draft.getReasons(Draft.java:56) ~[?:?]
        at org.ctp.coldstorage.inventory.draft.ViewDraft.setInventory(ViewDraft.java:156) ~[?:?]
        at org.ctp.coldstorage.inventory.draft.ViewDraft.setItemName(ViewDraft.java:264) ~[?:?]
        at org.ctp.coldstorage.nms.anvil.AnvilGUI_v1_13_R2$2$2.run(AnvilGUI_v1_13_R2.java:338) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
```
Best regards.

**Comment by Metamaniac** [comment]
Same exact thing here. Paper 1.13.2
